// Product data with Indian context
export interface Product {
  id: number
  name: string
  price: number
  originalPrice?: number
  category: string
  image: string
  rating: number
  reviews: number
  colors: string[]
  sizes: string[]
  isNew?: boolean
  onSale?: boolean
  description?: string
  tags?: string[]
}

export const products: Product[] = [
  {
    id: 1,
    name: "Embroidered Mirror Work Blouse",
    price: 3499,
    originalPrice: 4299,
    category: "Navratri Blouses",
    image: "/placeholder.svg?height=400&width=800",
    rating: 4.8,
    reviews: 120,
    colors: ["Pink", "Orange", "Green"],
    sizes: ["32", "34", "36", "38", "40"],
    isNew: false,
    onSale: true,
    description: "Handcrafted mirror work blouse with traditional Gujarati embroidery, perfect for Navratri celebrations.",
    tags: ["mirror-work", "traditional", "navratri", "handcrafted"],
  },
  {
    id: 2,
    name: "Bandhani Silk Blouse",
    price: 2899,
    category: "Navratri Blouses",
    image: "/placeholder.svg?height=400&width=800",
    rating: 5,
    reviews: 95,
    colors: ["Yellow", "Red", "Blue"],
    sizes: ["32", "34", "36", "38", "40"],
    isNew: true,
    onSale: false,
    description: "Traditional bandhani tie-dye silk blouse with intricate patterns, ideal for garba nights.",
    tags: ["bandhani", "silk", "navratri", "traditional"],
  },
  {
    id: 3,
    name: "Designer Chaniya Choli",
    price: 4999,
    originalPrice: 5999,
    category: "Lehenga Cholis",
    image: "/placeholder.svg?height=400&width=800",
    rating: 4.9,
    reviews: 78,
    colors: ["Royal Blue", "Maroon", "Emerald Green"],
    sizes: ["S", "M", "L", "XL"],
    isNew: true,
    onSale: true,
    description: "Stunning designer chaniya choli with heavy embroidery and mirror work, perfect for special Navratri celebrations.",
    tags: ["chaniya-choli", "designer", "navratri", "embroidered"],
  },
  {
    id: 4,
    name: "Kutch Embroidery Blouse",
    price: 3999,
    originalPrice: 4999,
    category: "Navratri Blouses",
    image: "/placeholder.svg?height=400&width=800",
    rating: 4.7,
    reviews: 62,
    colors: ["Black", "Maroon", "Teal"],
    sizes: ["32", "34", "36", "38", "40"],
    isNew: false,
    onSale: true,
    description: "Traditional Kutch embroidery blouse with intricate thread work and small mirrors, perfect for festive occasions.",
    tags: ["kutch", "embroidery", "traditional", "handcrafted"],
  },
  {
    id: 5,
    name: "Brocade Readymade Blouse",
    price: 2499,
    category: "Navratri Blouses",
    image: "/placeholder.svg?height=400&width=800",
    rating: 4.5,
    reviews: 108,
    colors: ["Gold", "Silver", "Copper"],
    sizes: ["32", "34", "36", "38", "40"],
    isNew: false,
    onSale: false,
    description: "Elegant brocade readymade blouse with golden zari work, versatile for multiple festive occasions.",
    tags: ["brocade", "readymade", "zari", "versatile"],
  },
  {
    id: 6,
    name: "Beaded Kundan Choker",
    price: 1899,
    category: "Jewelry",
    image: "/placeholder.svg?height=400&width=800",
    rating: 4.8,
    reviews: 45,
    colors: ["Gold", "Rose Gold", "Silver"],
    sizes: ["One Size"],
    isNew: false,
    onSale: false,
    description: "Stunning kundan choker with beaded details and adjustable chain, perfect for completing your Navratri look.",
    tags: ["kundan", "choker", "traditional", "handcrafted"],
  },
  {
    id: 7,
    name: "Cotton Garba Skirt",
    price: 2999,
    category: "Lehenga Cholis",
    image: "/placeholder.svg?height=400&width=800",
    rating: 4.6,
    reviews: 52,
    colors: ["Yellow", "Pink", "Orange"],
    sizes: ["S", "M", "L", "XL"],
    isNew: false,
    onSale: false,
    description: "Comfortable cotton skirt with traditional prints, perfect for extended garba nights.",
    tags: ["cotton", "skirt", "garba", "comfortable"],
  },
  {
    id: 8,
    name: "Bandhani Dupatta with Gota Work",
    price: 1299,
    originalPrice: 1599,
    category: "Dandiya Dupattas",
    image: "/placeholder.svg?height=400&width=800",
    rating: 4.7,
    reviews: 38,
    colors: ["Red", "Green", "Yellow"],
    sizes: ["One Size"],
    isNew: false,
    onSale: true,
    description: "Traditional bandhani dupatta with gota work border, perfect for adding a pop of color to your Navratri ensemble.",
    tags: ["bandhani", "dupatta", "gota", "traditional"],
  },
  {
    id: 9,
    name: "Designer Back Open Blouse",
    price: 3799,
    category: "Navratri Blouses",
    image: "/placeholder.svg?height=400&width=800",
    rating: 4.9,
    reviews: 75,
    colors: ["Turquoise", "Purple", "Red"],
    sizes: ["32", "34", "36", "38", "40"],
    isNew: true,
    onSale: false,
    description: "Stylish back open blouse with dori tie-up and intricate embroidery, perfect for making a statement at garba nights.",
    tags: ["back-open", "designer", "embroidery", "trendy"],
  },
  {
    id: 10,
    name: "Oxidized Silver Anklets",
    price: 899,
    category: "Accessories",
    image: "/placeholder.svg?height=400&width=800",
    rating: 4.5,
    reviews: 42,
    colors: ["Silver"],
    sizes: ["One Size"],
    isNew: false,
    onSale: false,
    description: "Traditional oxidized silver anklets with ghungroo bells, perfect for adding authentic touch to your dandiya outfit.",
    tags: ["anklets", "oxidized", "ghungroo", "traditional"],
  },
  {
    id: 11,
    name: "Handcrafted Navratri Earrings",
    price: 599,
    category: "Accessories",
    image: "/placeholder.svg?height=400&width=800",
    rating: 4.8,
    reviews: 32,
    colors: ["Gold", "Silver", "Rose Gold"],
    sizes: ["One Size"],
    isNew: true,
    onSale: false,
    description: "Beautiful handcrafted earrings with traditional motifs, perfect for completing your Navratri look.",
    tags: ["earrings", "handcrafted", "traditional", "lightweight"],
  },
  {
    id: 12,
    name: "Multicolor Bandhej Dupatta",
    price: 1499,
    category: "Dandiya Dupattas",
    image: "/placeholder.svg?height=400&width=800",
    rating: 4.6,
    reviews: 55,
    colors: ["Multicolor"],
    sizes: ["One Size"],
    isNew: false,
    onSale: false,
    description: "Vibrant multicolor bandhej dupatta with mirror work border, perfect for adding flair to your Navratri ensemble.",
    tags: ["bandhej", "multicolor", "mirror-work", "traditional"],
  },
  {
    id: 13,
    name: "Embroidered Blouse Fabric",
    price: 1299,
    originalPrice: 1599,
    category: "Navratri Blouses",
    image: "/placeholder.svg?height=400&width=800",
    rating: 4.4,
    reviews: 29,
    colors: ["Pink", "Blue", "Green"],
    sizes: ["One Size"],
    isNew: false,
    onSale: true,
    description: "Pre-embroidered blouse fabric with mirror work and thread embroidery, ready to be stitched to your measurements.",
    tags: ["fabric", "embroidered", "mirror-work", "customizable"],
  },
  {
    id: 14,
    name: "Traditional Dandiya Sticks",
    price: 499,
    category: "Accessories",
    image: "/placeholder.svg?height=400&width=800",
    rating: 4.3,
    reviews: 48,
    colors: ["Multicolor", "Red-Gold", "Green-Gold"],
    sizes: ["One Size"],
    isNew: false,
    onSale: false,
    description: "Beautifully decorated dandiya sticks with mirror work and bells, perfect for traditional Navratri celebrations.",
    tags: ["dandiya", "sticks", "traditional", "handpainted"],
  },
  {
    id: 15,
    name: "Zari Border Dupatta",
    price: 999,
    category: "Dandiya Dupattas",
    image: "/placeholder.svg?height=400&width=800",
    rating: 4.5,
    reviews: 37,
    colors: ["Red", "Green", "Yellow", "Blue"],
    sizes: ["One Size"],
    isNew: false,
    onSale: false,
    description: "Elegant dupatta with traditional zari border, perfect for adding a touch of sophistication to your Navratri outfit.",
    tags: ["zari", "dupatta", "elegant", "traditional"],
  },
  {
    id: 16,
    name: "Kutch Embroidered Potli Bag",
    price: 799,
    category: "Accessories",
    image: "/placeholder.svg?height=400&width=800",
    rating: 4.7,
    reviews: 31,
    colors: ["Multicolor", "Red", "Blue"],
    sizes: ["One Size"],
    isNew: true,
    onSale: false,
    description: "Traditional potli bag with authentic Kutch embroidery, perfect for carrying essentials during Navratri celebrations.",
    tags: ["potli", "bag", "kutch", "embroidered"],
  },
  {
    id: 17,
    name: "Navratri Special Bangles Set",
    price: 399,
    category: "Accessories",
    image: "/placeholder.svg?height=400&width=800",
    rating: 4.4,
    reviews: 65,
    colors: ["Multicolor", "Gold-Red", "Gold-Green"],
    sizes: ["2.4", "2.6", "2.8"],
    isNew: false,
    onSale: false,
    description: "Set of 12 colorful bangles with traditional designs, perfect for completing your Navratri look.",
    tags: ["bangles", "set", "colorful", "traditional"],
  },
  {
    id: 18,
    name: "Ready-to-Wear Saree",
    price: 3999,
    originalPrice: 4599,
    category: "Custom Creations",
    image: "/placeholder.svg?height=400&width=800",
    rating: 4.8,
    reviews: 42,
    colors: ["Pink", "Blue", "Green", "Yellow"],
    sizes: ["S", "M", "L", "XL"],
    isNew: true,
    onSale: true,
    description: "Pre-draped saree with attached petticoat and blouse, perfect for those who want the saree look without the hassle of draping.",
    tags: ["ready-to-wear", "saree", "convenient", "modern"],
  },
  {
    id: 19,
    name: "Mirror Work Crop Top",
    price: 1599,
    category: "Navratri Blouses",
    image: "/placeholder.svg?height=400&width=800",
    rating: 4.6,
    reviews: 38,
    colors: ["Black", "White", "Red"],
    sizes: ["S", "M", "L"],
    isNew: true,
    onSale: false,
    description: "Contemporary crop top with traditional mirror work, perfect for fusion Navratri outfits.",
    tags: ["crop-top", "mirror-work", "fusion", "contemporary"],
  },
  {
    id: 20,
    name: "Handcrafted Waist Belt",
    price: 899,
    category: "Accessories",
    image: "/placeholder.svg?height=400&width=800",
    rating: 4.5,
    reviews: 27,
    colors: ["Gold", "Silver", "Copper"],
    sizes: ["S", "M", "L"],
    isNew: false,
    onSale: false,
    description: "Traditional waist belt with bells and mirror work, perfect for accentuating your Navratri outfit.",
    tags: ["waist-belt", "kamarbandh", "traditional", "handcrafted"],
  }
]

export const categories = [
  { name: "Navratri Blouses", slug: "navratri-blouses", count: 24 },
  { name: "Lehenga Cholis", slug: "lehenga-cholis", count: 18 },
  { name: "Custom Creations", slug: "custom-creations", count: 15 },
  { name: "Dandiya Dupattas", slug: "dandiya-dupattas", count: 12 },
  { name: "Accessories", slug: "accessories", count: 16 },
  { name: "Jewelry", slug: "jewelry", count: 8 },
]

export const tags = [
  "traditional",
  "modern",
  "festive",
  "navratri",
  "garba",
  "dandiya",
  "cotton",
  "silk",
  "georgette",
  "bandhani",
  "bandhej",
  "embroidered",
  "mirror-work",
  "gota-patti",
  "handcrafted",
  "kutch",
  "gujarati",
  "chaniya-choli",
  "lehenga",
  "blouse",
  "dupatta",
  "custom",
  "readymade",
  "designer",
]
